version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /FSSHTTPWOPIInspector/Source
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /FSSHTTPWOPIInspector/Test/WOPIautomation/WOPIautomation
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /MAPIInspector/Source
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /MAPIInspector/Test/MAPIAutomationTest/MAPIAutomationTest
    schedule:
      interval: daily
