using BlockParser;

namespace MAPIInspector.Parsers
{
    /// <summary>
    /// 2.2.5.1.2.2 OP_REPLY and OP_OOF_REPLY ActionData Structure
    /// This type is specified in MS-OXORULE section 2.2.5.1.2.2 OP_REPLY and OP_OOF_REPLY ActionData Structure for Standard Rules
    /// </summary>
    public class OP_REPLY_and_OP_OOF_REPLY_ActionData_forStandard : Block
    {
        /// <summary>
        /// A Folder ID structure, as specified in [MS-OXCDATA] section 2.2.1.1, that identifies the folder that contains the reply template.
        /// </summary>
        public FolderID ReplyTemplateFID;

        /// <summary>
        /// A Message ID structure, as specified in [MS-OXCDATA] section 2.2.1.2, that identifies the FAI message being used as the reply template.
        /// </summary>
        public MessageID ReplyTemplateMID;

        /// <summary>
        /// A GUID that is generated by the client in the process of creating a reply template.
        /// </summary>
        public BlockGuid ReplyTemplateGUID;

        /// <summary>
        /// Parse the OP_REPLY_and_OP_OOF_REPLY_ActionData_forStandard structure.
        /// </summary>
        protected override void Parse()
        {
            ReplyTemplateFID = Parse<FolderID>();
            ReplyTemplateMID = Parse<MessageID>();
            ReplyTemplateGUID = Parse<BlockGuid>();
        }

        protected override void ParseBlocks()
        {
            AddLabeledChild(ReplyTemplateFID, "ReplyTemplateFID");
            AddLabeledChild(ReplyTemplateMID, "ReplyTemplateMID");
            this.AddChildGuid(ReplyTemplateGUID, "ReplyTemplateGUID");
        }
    }
}
