name: $(Year:yy).0.$(date:yy)$(DayOfYear)$(rev:.rr)

trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

stages:
- stage: Release
  jobs:
  - job: Sign
    steps:
    - checkout: self
      clean: true
      submodules: recursive

    # Download latest drop from build task
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: '66af1341-9a01-4509-a5ff-5d71bf70ed37'
        pipeline: '17'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: UseDotNet@2
      displayName: 'Install .NetCore 2.x'
      inputs:
        version: '2.x'

    - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
      displayName: 'ESRP CodeSigning'
      inputs:
        ConnectedServiceName: 'ESRP CodeSigning Service connection'
        FolderPath: '$(System.ArtifactsDirectory)/drop'
        Pattern: '*.dll'
        signConfigType: inlineSignParams
        inlineOperation: |
          [
                  {
                      "KeyCode" : "CP-230012",
                      "OperationCode" : "SigntoolSign",
                      "Parameters" : {
                          "OpusName" : "Microsoft",
                          "OpusInfo" : "http://www.microsoft.com",
                          "FileDigest" : "/fd \"SHA256\"",
                          "PageHash" : "/NPH",
                          "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                      },
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  },
                  {
                      "KeyCode" : "CP-230012",
                      "OperationCode" : "SigntoolVerify",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  }
              ]

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(System.ArtifactsDirectory)/drop'

    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'GitHub OfficeDev / Office-Inspectors-for-Fiddler'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: '$(Build.BuildNumber)'
        assets: |
          $(Build.ArtifactStagingDirectory)/drop/*.dll
          $(Build.ArtifactStagingDirectory)/drop/*.pdb
        isDraft: true
        isPreRelease: true
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
        title: MAPIFiddlerInspector & FSSHTTPandWOPIFiddlerInspector ($(Build.BuildNumber))