using System;

namespace MAPIInspector.Parsers
{
    /// <summary>
    /// Section 2.2.1.13.1   RopGetHierarchyTable ROP Request Buffer
    /// </summary>
    [Flags]
    public enum HierarchyTableFlags : byte
    {
        /// <summary>
        /// the hierarchy table lists folders from all levels under the folder
        /// </summary>
        Depth = 0x04,

        /// <summary>
        /// Deferred Errors
        /// </summary>
        DeferredErrors = 0x08,

        /// <summary>
        /// The hierarchy table notifications to the client are disabled
        /// </summary>
        NoNotifications = 0x10,

        /// <summary>
        /// The hierarchy table lists only the folders that are soft deleted
        /// </summary>
        SoftDeletes = 0x20,

        /// <summary>
        /// The columns that contain string data are returned in Unicode format
        /// </summary>
        UseUnicode = 0x40,

        /// <summary>
        /// The notifications generated by the client's actions on the hierarchy table are suppressed
        /// </summary>
        SuppressesNotifications = 0x80
    }
}