# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build MAPIInspector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Machine setup
      shell: pwsh
      run: ./scripts/machine-setup.ps1

    - name: "Build"
      shell: pwsh
      run: |
        $path = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
        & $path\MSBuild\Current\Bin\amd64\msbuild.exe /m /p:Configuration="Release" ./MAPIInspector/Source/MAPIInspector.sln
        & $path\MSBuild\Current\Bin\amd64\msbuild.exe /m /p:Configuration="Release" ./MAPIInspector/Test/MAPIAutomationTest/MAPIAutomationTest.sln
        & $path\MSBuild\Current\Bin\amd64\msbuild.exe /m /p:Configuration="Release" ./FSSHTTPWOPIInspector/Source/FSSHTTPandWOPIInspector.sln
        & $path\MSBuild\Current\Bin\amd64\msbuild.exe /m /p:Configuration="Release" ./FSSHTTPWOPIInspector/Test/WOPIautomation/WOPIautomation.sln

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          .\MAPIInspector\Source\bin\Release\MAPIFiddlerInspector.dll
          .\MAPIInspector\Source\bin\Release\MAPIFiddlerInspector.pdb
          .\FSSHTTPWOPIInspector\Source\bin\Release\FSSHTTPandWOPIFiddlerInspector.dll
          .\FSSHTTPWOPIInspector\Source\bin\Release\FSSHTTPandWOPIFiddlerInspector.pdb