# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build MAPIInspector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 4.6.1
    - name: Download and Install .NET Framework 4.6.1 Developer Pack
      run: |
        # Download the .NET Framework 4.6.1 Developer Pack
        Invoke-WebRequest -Uri https://aka.ms/msbuild/developerpacks/dotnetfx461devpack.exe -OutFile dotnetfx461devpack.exe

        # Install the Developer Pack silently
        Start-Process -FilePath dotnetfx461devpack.exe -ArgumentList "/q" -Wait

        # Clean up the installer file
        Remove-Item -Path dotnetfx461devpack.exe
    - name: Restore dependencies
      run: dotnet restore ./MAPIInspector/Source/MAPIInspector.sln
    - name: Download and Install Fiddler
      shell: pwsh
      run: |
        # Define the URL for the Fiddler installer (check for the latest version on the Telerik website)
        $FiddlerInstallerUrl = "https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe"

        # Define the path where you want to save the installer
        $InstallerPath = "$env:USERPROFILE\Downloads\FiddlerSetup.exe"

        # Download Fiddler installer
        Invoke-WebRequest -Uri $FiddlerInstallerUrl -OutFile $InstallerPath

        # Install Fiddler silently
        Start-Process -FilePath $InstallerPath -ArgumentList "/S" -Wait

    - name: "Build"
      shell: pwsh
      run: |
        $path = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
        & $path\MSBuild\Current\Bin\amd64\msbuild.exe /m /p:Configuration="Release" ./MAPIInspector/Source/MAPIInspector.sln